#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 06 15:14:59 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=true
